components:
  schemas:
    dvcsa.Models.User:
      description: Class dvcsa.Models.User
      properties:
        Id:
          format: int32
          type: integer
          x-field-kind: normal
          x-field-original-type: System.int
          x-field-type: integer
        Name:
          type: string
          x-field-kind: normal
          x-field-original-type: System.string
          x-field-type: string
        Password:
          type: string
          x-field-kind: normal
          x-field-original-type: System.string
          x-field-type: string
      type: object
      x-class-type: dvcsa.Models.User
      x-source-file: Models/User.cs~~4
info:
  title: dvcsa
  version: "0.1"
openapi: 3.0.0
paths:
  /api/.Env:
    get:
      operationId: api_.Env_GET
      responses:
        default:
          description: Default response
      x-name: api_.Env_GET
      x-source: Controllers/EnvController.cs~~9
    x-name: api_.Env
  /api/Users:
    get:
      operationId: api_Users_GET
      parameters:
      - in: query
        name: name
        schema:
          type: string
          x-field-kind: normal
          x-field-original-type: System.string
          x-field-type: string
        x-category: query parameter
      responses:
        default:
          description: Default response
      x-name: api_Users_GET
      x-source: Controllers/UsersController.cs~~22
    post:
      operationId: api_Users_POST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dvcsa.Models.User'
        x-code: ""
      responses:
        default:
          description: Default response
      x-name: api_Users_POST
      x-source: Controllers/UsersController.cs~~34
    x-name: api_Users
  /api/Users/search:
    get:
      operationId: api_Users_search_GET
      parameters:
      - in: query
        name: name
        schema:
          type: string
          x-field-kind: normal
          x-field-original-type: System.string
          x-field-type: string
        x-category: query parameter
      responses:
        default:
          description: Default response
      x-name: api_Users_search_GET
      x-source: Controllers/UsersController.cs~~42
    x-name: api_Users_search
servers:
- description: Default server
  url: http://localhost:9000
